package com.wuav.client.bll.helpers;

public enum EventType {
    SET_CURRENT_PROJECT,
    UPDATE_TABLE,
    START_LOADING_PROJECTS,
    UPDATE_USER_TABLE,

    EXPORT_EMAIL,
    REFRESH_DEVICE_LIST, SET_CURRENT_DEVICE, SHOW_NOTIFICATION, FILL_TABLE,
}
